### ISSUE TITLE
Form Component not working

### ISSUE THREAD

**Issue by nandotess** [KenticoDevTrev/TinyMCE_Wysiwyg#3]
I have added all the **FormComponents** files (only the files related to this, not related to the inline editor), and I'm trying to use them as a form component from my widget.

```
// Text
[EditingComponent(TinyMCEInputComponent.IDENTIFIER, Order = 1, Label = "Text")]
public string Text { get; set; } = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
```

I can debug the JS (TinyMCEInputComponent.js)... I can see the hidden input element is created... I can see the editor element is created... but I can't see the editor.

My Kentico version is **v12.0.56**.

**Questions**: am I able to use the form component, only this feature, without the other files? Do you have any tip to help me to debug this issue?

Thank you so much for any help.

A quick look into the files imported from your repository:
![image](https://user-images.githubusercontent.com/804109/74187325-50ff7100-4c1a-11ea-9faf-16ac47da88c7.png)

**Comment by nandotess** [comment]
Clearly it's an editor CSS/visibility problem. Not sure if the styles on **TextEditor.css** are enough. I will continue debugging, any updates I will provide here.

**Comment by nandotess** [comment]
The problem was just styles.

- The JS property `config.skin_url` is linking to a TinyMCE skin folder that doesn't exist in this repo, but I can understand why it is no in the TinyMCE folder (would be loaded and conflicted with the website). So I have download from TinyMCE website the ui skin package and I have imported to my project in a separate folder: `skin_url: '/Content/assets/tinymce/skins/ui/oxide'`.

- The JS property `config.content_css` is linking to the Form Component style, which also doesn't exist in this repo. So I have download from TinyMCE website the content skin package and I have imported to my project in a separate folder: `content_css: '/Content/assets/tinymce/skins/content/default/content.min.css'`.

Now I can see the TinyMCE editor, I just need to continue to improve the styles to avoid any conflicts with the website styles.

**Comment by KenticoDevTrev** [comment]
Sounds good! Just so you know when Kentico finishes up the froala editor,
meaning the links work properly and they have the widget configuration
version or it going, we are largely going to stop the tiny MCE as it was
only a stop gap till Kentico released their solution. I hear they are
working on both improvements.
